# Generated by Django 4.1.5 on 2023-01-31 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileImportResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resource_id", models.UUIDField(db_index=True, unique=True)),
                ("result_is_successful", models.BooleanField()),
                ("result_error", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnprocessedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.UUIDField(db_index=True, unique=True)),
                ("mime_type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=99)),
                ("url", models.CharField(max_length=300)),
            ],
        ),
    ]
