# Generated by Django 4.1.5 on 2023-02-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["calendar", "start"], name="parsing_eve_calenda_9d25c6_idx"
            ),
        ),
    ]
