# Generated by Django 4.1.5 on 2023-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0002_event_parsing_eve_calenda_9d25c6_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subject",
            field=models.CharField(max_length=250),
        ),
    ]
