# Generated by Django 4.1.5 on 2023-02-27 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0003_alter_event_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resource_id", models.UUIDField(db_index=True, unique=True)),
                ("status", models.CharField(max_length=15)),
                ("detail", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
