# Generated by Django 4.1.5 on 2023-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0006_calendar_when_created_at_source"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("end__gt", models.F("start"))), name="end_after_start"
            ),
        ),
    ]
