# Generated by Django 4.1.5 on 2023-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0008_alter_event_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
