# Generated by Django 4.1.5 on 2023-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0009_alter_calendar_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
