# Generated by Django 4.1.5 on 2023-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing", "0011_calendar_package_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="package_id",
            field=models.UUIDField(default="89d6f7bd-4164-48a9-aec5-3cab2cb32c9c"),
            preserve_default=False,
        ),
    ]
